# 3 tags: update, delete and update
AMMOS_CONVERSION = {
    'AMMO_PISTOL': {
        'update': {'Name': 'AMMO_9MM', 'AmmoMax': 60, 'AmmoMax50': 90, 'AmmoMax100': 120},
        'delete': True,
    },
    'AMMO_SMG': {
        'update': [
            {'Name': 'AMMO_38S', 'AmmoMax': 60, 'AmmoMax50': 90, 'AmmoMax100': 120},
            {'Name': 'AMMO_40C', 'AmmoMax': 60, 'AmmoMax50': 90, 'AmmoMax100': 120},
            {'Name': 'AMMO_45C', 'AmmoMax': 60, 'AmmoMax50': 90, 'AmmoMax100': 120},
            {'Name': 'AMMO_50C', 'AmmoMax': 60, 'AmmoMax50': 90, 'AmmoMax100': 120},
        ],
        'delete': True,
    },
    'AMMO_RIFLE': {
        'update': {'Name': 'AMMO_556', 'AmmoMax': 90, 'AmmoMax50': 135, 'AmmoMax100': 180},
        'delete': True,
    },
    'AMMO_MG': {
        'update': {'Name': 'AMMO_762', 'AmmoMax': 90, 'AmmoMax50': 135, 'AmmoMax100': 180},
        'delete': True,
    },
    'AMMO_SNIPER': {
        'update': {'Name': 'AMMO_50BMG', 'AmmoMax': 30, 'AmmoMax50': 45, 'AmmoMax100': 60},
        'delete': True,
    },
    # AMMO_MINIGUN is also used for some vehicle weapons, so it's updateed into a
    # new ammo type for WEAPON_MINIGUN 
    'AMMO_MINIGUN': {
        'update': {'Name': 'AMMO_762MNG', 'AmmoMax': 300, 'AmmoMax50': 450, 'AmmoMax100': 600},
    },
    'AMMO_SHOTGUN': {
        'update': [
            {'Name': 'AMMO_12G', 'AmmoMax': 40, 'AmmoMax50': 60, 'AmmoMax100': 80},
            {'Name': 'AMMO_20G', 'AmmoMax': 50, 'AmmoMax50': 75, 'AmmoMax100': 100},
            {'Name': 'AMMO_18MM', 'AmmoMax': 20, 'AmmoMax50': 30, 'AmmoMax100': 40},
        ],
        'delete': True,
    },
    'AMMO_STUNGUN': {},
    'AMMO_SNIPER_REMOTE': {},
    'AMMO_FIREEXTINGUISHER': {},
    'AMMO_PETROLCAN': {},
    'AMMO_MINIGUN': {},
    'AMMO_GRENADELAUNCHER': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_GRENADELAUNCHER_SMOKE': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_RPG': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_STINGER': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_GRENADE': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_BALL': {},
    'AMMO_STICKYBOMB': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_SMOKEGRENADE': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_BZGAS': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_FLARE': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_MOLOTOV': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_TANK': {},
    'AMMO_SPACE_ROCKET': {},
    'AMMO_PLANE_ROCKET': {},
    'AMMO_PLAYER_LASER': {},
    'AMMO_ENEMY_LASER': {},
    'AMMO_BIRD_CRAP': {},
    'AMMO_MG_ARMORPIERCING': {},
    'AMMO_MG_FMJ': {},
    'AMMO_MG_INCENDIARY': {},
    'AMMO_MG_TRACER': {},
    'AMMO_PISTOL_FMJ': {},
    'AMMO_PISTOL_HOLLOWPOINT': {},
    'AMMO_PISTOL_INCENDIARY': {},
    'AMMO_PISTOL_TRACER': {},
    'AMMO_RIFLE_ARMORPIERCING': {},
    'AMMO_RIFLE_FMJ': {},
    'AMMO_RIFLE_INCENDIARY': {},
    'AMMO_RIFLE_TRACER': {},
    'AMMO_SMG_FMJ': {},
    'AMMO_SMG_HOLLOWPOINT': {},
    'AMMO_SMG_INCENDIARY': {},
    'AMMO_SMG_TRACER': {},
    'AMMO_SNIPER_ARMORPIERCING': {},
    'AMMO_SNIPER_EXPLOSIVE': {},
    'AMMO_SNIPER_FMJ': {},
    'AMMO_SNIPER_INCENDIARY': {},
    'AMMO_SNIPER_TRACER': {},
    'AMMO_SHOTGUN_ARMORPIERCING': {},
    'AMMO_SHOTGUN_EXPLOSIVE': {},
    'AMMO_SHOTGUN_HOLLOWPOINT': {},
    'AMMO_SHOTGUN_INCENDIARY': {},
    'AMMO_FIREWORK': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_RAILGUN': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_FLAREGUN': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_HOMINGLAUNCHER': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_PROXMINE': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_SNOWBALL': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_PIPEBOMB': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_RAYPISTOL': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_HAZARDCAN': {},
    'AMMO_TRANQUILIZER': {},
    'AMMO_FERTILIZERCAN': {},
    'AMMO_EMPLAUNCHER': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_ACIDPACKAGE': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_RAILGUNXM3': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
    'AMMO_SNOWLAUNCHER': {'update': {'AmmoMax': 4, 'AmmoMax50': 6, 'AmmoMax100': 8},},
}